import turtle


class Bob:
    bob = turtle.Turtle()
    bob.width(5)
    bob.speed(40)

    def body():
        bob.penup()
        bob.goto(-105, 50)
        bob.right(90)
        bob.pendown()
        bob.color("#fcd730")
        bob.fillcolor("#fcd730")
        bob.begin_fill()
        bob.circle(100, -180)
        bob.right(180)
        bob.forward(120)
        bob.right(90)
        bob.forward(200)
        bob.right(90)
        bob.forward(120)
        bob.end_fill()

    body()

    def glasses():
        bob.penup()
        bob.goto(-107, 60)
        bob.pendown()
        bob.right(90)
        bob.color("#424242")
        bob.fillcolor("#424242")
        bob.begin_fill()
        bob.forward(204)
        bob.right(90)
        bob.forward(20)
        bob.right(90)
        bob.forward(204)
        bob.right(90)
        bob.forward(20)
        bob.end_fill()
        bob.penup()
        bob.goto(-50, 50)
        bob.pendown()
        bob.color("grey")
        bob.dot(100)
        bob.color("white")
        bob.dot(70)
        bob.penup()
        bob.goto(40, 50)
        bob.pendown()
        bob.color("grey")
        bob.dot(100)
        bob.color("white")
        bob.dot(70)

    glasses()

    def eye():
        bob.penup()
        bob.goto(-50, 50)
        bob.pendown()
        bob.color("#40322b")
        bob.dot(30)
        bob.penup()
        bob.goto(-54, 54)
        bob.pendown()
        bob.color("white")
        bob.dot(10)
        bob.penup()
        bob.goto(40, 50)
        bob.pendown()
        bob.color("#40322b")
        bob.dot(30)
        bob.penup()
        bob.goto(36, 54)
        bob.pendown()
        bob.color("white")
        bob.dot(10)

    eye()

    def mouth():
        bob.penup()
        bob.goto(12, -3)
        bob.pendown()
        bob.right(180)
        bob.color("#424242")
        bob.circle(-15, 180)

    mouth()

    def shirt():
        bob.penup()
        bob.goto(-50, -30)
        bob.color("#4d78c4")
        bob.pendown()
        bob.fillcolor("#4d78c4")
        bob.begin_fill()
        bob.right(90)
        bob.forward(100)
        bob.right(90)
        bob.forward(40)
        bob.left(90)
        bob.forward(47)
        bob.right(90)
        bob.circle(-102, 180)
        bob.right(90)
        bob.forward(47)
        bob.left(90)
        bob.forward(40)
        bob.right(90)
        bob.forward(20)
        bob.end_fill()
        # bag
        bob.penup()
        bob.goto(-25, -50)
        bob.pendown()
        bob.color("#294f91")
        bob.fillcolor()
        bob.begin_fill()
        bob.forward(50)
        bob.right(90)
        bob.forward(10)
        bob.circle(-30, 180)
        bob.forward(10)
        bob.right(90)
        bob.forward(20)
        bob.end_fill()

    shirt()

    def crown():
        bob.penup()
        bob.goto(-50, 140)
        bob.pendown()
        bob.color("#f7ebe6")
        bob.fillcolor("#f7ebe6")
        bob.begin_fill()
        bob.circle(7, -180)
        bob.right(180)
        bob.forward(85)
        bob.circle(-7, 180)
        bob.forward(85)
        bob.end_fill()
        bob.penup()
        bob.goto(-50, 157)
        bob.pendown()
        bob.color("#e3be66")
        bob.fillcolor("#e3be66")
        bob.begin_fill()
        bob.right(90)
        bob.forward(5)
        bob.right(90)
        bob.forward(85)
        bob.right(90)
        bob.forward(5)
        bob.right(90)
        bob.forward(85)
        bob.color("#a761ed")
        bob.penup()
        bob.goto(-49, 167)
        bob.right(90)
        bob.pendown()
        bob.fillcolor("#a761ed")
        bob.begin_fill()
        bob.circle(-42, 180)
        bob.right(90)
        bob.forward(84)
        bob.end_fill()
        bob.penup()
        bob.color("#e3be66")
        bob.fillcolor("#e3be66")
        bob.goto(-10, 157)
        bob.pendown()
        bob.right(90)
        bob.forward(60)
        bob.circle(-2.5, 180)
        bob.forward(60)
        bob.end_fill()
        bob.penup()
        bob.color("#e3be66")
        bob.goto(36, 165)
        bob.left(170)
        bob.pendown()
        bob.forward(30)
        bob.left(75)
        bob.forward(50)
        bob.penup()
        bob.right(65)
        bob.right(180)
        bob.color("#e3be66")
        bob.goto(-49, 165)
        bob.right(170)
        bob.pendown()
        bob.forward(30)
        bob.right(75)
        bob.forward(50)
        bob.left(65)

    crown()

    def pahkoom():
        bob.penup()
        bob.goto(-50, -30)
        bob.left(60)
        bob.pendown()
        bob.color("#fa431e")
        bob.fillcolor("#fa431e")
        bob.begin_fill()
        bob.forward(68)
        bob.left(120)
        bob.forward(120)
        bob.left(90)
        bob.forward(20)
        bob.left(65)
        bob.forward(95)
        bob.end_fill()

        bob.penup()
        bob.goto(-50, -30)
        bob.left(35)
        bob.pendown()
        bob.color("#f7ebe6")
        bob.fillcolor("#f7ebe6")
        bob.begin_fill()
        bob.left(40)
        bob.forward(80)
        bob.left(140)
        bob.forward(15)
        bob.left(48)
        bob.forward(73)
        bob.end_fill()
        # right
        bob.penup()
        bob.goto(40, -30)
        bob.right(60)
        bob.pendown()
        bob.color("#fa431e")
        bob.fillcolor("#fa431e")
        bob.begin_fill()
        bob.left(120)
        bob.forward(68)
        bob.right(120)
        bob.forward(120)
        bob.right(90)
        bob.forward(20)
        bob.right(65)
        bob.forward(95)
        bob.end_fill()

        bob.penup()
        bob.goto(40, -30)
        bob.right(35)
        bob.pendown()
        bob.color("#f7ebe6")
        bob.fillcolor("#f7ebe6")
        bob.begin_fill()
        bob.right(40)
        bob.forward(80)
        bob.right(140)
        bob.forward(15)
        bob.right(48)
        bob.forward(73)
        bob.end_fill()
        bob.right(30)

    pahkoom()

    def shoe():
        # left
        bob.penup()
        bob.goto(-50, -160)
        bob.color("#2b2b2a")
        bob.pendown()
        bob.fillcolor("#2b2b2a")
        bob.begin_fill()
        bob.forward(30)
        bob.circle(10, 180)
        bob.forward(30)
        bob.circle(10, 180)
        bob.end_fill()
        # right
        bob.penup()
        bob.right(180)
        bob.goto(40, -180)
        bob.color("#2b2b2a")
        bob.pendown()
        bob.fillcolor("#2b2b2a")
        bob.begin_fill()
        bob.forward(30)
        bob.circle(10, 180)
        bob.forward(30)
        bob.circle(10, 180)
        bob.end_fill()

    shoe()

    bob.penup()
    bob.goto(100, 90)
    bob.write("congratulation!", font=("Arial", 30, "normal"))

    turtle.exitonclick()
